### ISSUE TITLE
Game crashing when clearing an coordinate input

### ISSUE THREAD

**Issue by dsadriel** [PouekDEV/CList#28]
When the coordinate input for creating a new waypoint is cleared, the game crashes due to an error when trying to parse the empty string `""` as an Integer.

## Possible solution:
On the `CListWaypointConfig.java` file, under the `keyPressed` function, check if x, y and z inputs are not empty before trying to convert them to integer. 

## Error log:
```
[11:35:55] [Render thread/ERROR]:
 Reported exception thrown!
net.minecraft.class_148: keyPressed event handler
	at net.minecraft.class_437.method_25412(class_437.java:472) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_1466(class_309.java:414) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_22678(class_309.java:503) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_22676(class_309.java:503) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.3.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) ~[lwjgl-glfw-3.3.3.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:200) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:218) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:287) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1342) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.10.jar:?]
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:?]
	at java.base/java.lang.Integer.parseInt(Unknown Source) ~[?:?]
	at java.base/java.lang.Integer.parseInt(Unknown Source) ~[?:?]
	at one.pouekdev.coordinatelist.CListWaypointConfig.method_25404(CListWaypointConfig.java:176) ~[coordinatelist-1.6.1-1.20.6.jar:?]
	at net.minecraft.class_309.method_1454(class_309.java:418) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:467) ~[client-intermediary.jar:?]
	... 16 more
```

**Comment by PouekDEV** [comment]
Hey thanks good catch! I knew I've forgotten about something when changing how the waypoint data is stored.
